apiVersion: istio.openshift.com/v1alpha3
kind: ControlPlane
metadata:
  name: istio-demo
spec:
  istio:
    global:
      hub: openshift-istio-tech-preview
      tag: 0.10.0
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 128Mi
      mtls: true
      disablePolicyChecks: true
      policyCheckFailOpen: false
      # imagePullSecrets:
      #   - MyPullSecret

    gateways:
      istio-egressgateway:
        autoscaleEnabled: false
        autoscaleMin: 1
        autoscaleMax: 5
      istio-ingressgateway:
        autoscaleEnabled: false
        autoscaleMin: 1
        autoscaleMax: 5
        ior_enabled: false

    mixer:
      policy:
        autoscaleEnabled: false

      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G

    pilot:
      autoscaleEnabled: false
      traceSampling: 100.0

    kiali:
      enabled: true
      hub: kiali
      tag: v0.16.2
      dashboard:
        user: admin
        passphrase: admin

    tracing:
      enabled: true
